### ISSUE TITLE
language plugin not found

### ISSUE THREAD

**Issue by ghost** [ChillMagic/VirtualNES#1]
Hi

After building and running VituaNES it says 
`Language plug-in is not found.`

and even when I copy EN.vlp to the built folder it says
`Language plug-in load failed.`

Do you have any idea what's wrong then ?

**Comment by ChillMagic** [comment]
> Hi
> 
> After building and running VituaNES it says `Language plug-in is not found.`
> 
> and even when I copy EN.vlp to the built folder it says `Language plug-in load failed.`
> 
> Do you have any idea what's wrong then ?


This repository contains two vcxproj projects, one is `VirtuaNES.vcxproj`, and the other is `ldk/LDK.vcxproj`.

Build `ldk/LDK.vcxproj` and place the output files in the same directory as `VirtuaNES.exe`, then it should work properly.

**Comment by ghost** [comment]
@ChillMagic Thank you very much, now it's working 👍

**Comment by ghost** [comment]
@ChillMagic is there a way to build with Brazilian or French res files ?

**Comment by ChillMagic** [comment]
> @ChillMagic is there a way to build with Brazilian or French res files ?

1. Put `Brazilian.res` or `French.res` in ldk/res
2. Add these files to ldk project (like `*.res` in ldk/res)
3. Build ldk project

**Comment by ghost** [comment]
@ChillMagic But when I build ldk and copy Languages.vlp, VirtuaNes is always in English.

**Comment by ChillMagic** [comment]
> @ChillMagic But when I build ldk and copy Languages.vlp, VirtuaNes is always in English.

The choice of language is automatically inferred based on the `locale` settings of the Windows system. The `Languages.vlp` built by the ldk project (which could also be a collection of several `.vlp` files) provides a list of languages for the operating system to determine which language to use. You can try to construct a `.vlp` with only a `.rc` or `.res` file of a particular language.

**Comment by ghost** [comment]
@ChillMagic I see, I think it's time to change this behavior and try to get the list of languages and apply directly the language to the emulator, I am not that good with C languages overall, but I will try.
Thank you so much for the information.

**Comment by ChillMagic** [comment]
> @ChillMagic I see, I think it's time to change this behavior and try to get the list of languages and apply directly the language to the emulator, I am not that good with C languages overall, but I will try. Thank you so much for the information.

This is a great idea. The VirtuaNES project is rather old, with the entire project written based on the MFC framework, which is outdated nowadays.
I am trying to migrate it to Linux/MacOS and am still considering which GUI framework to choose. Even though MFC is old, it comes with the Windows system, which means the binary size of the packaged program is smaller and uses fewer resources. If the GUI framework is replaced, this advantage may be lost.

**Comment by ghost** [comment]
@ChillMagic 
I suggest ImGUI
